<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>elision</string>
	</array>
	<key>name</key>
	<string>Elision</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>multi-line comment blocks</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>single-line comment blocks</string>
			<key>match</key>
			<string>//.*\n</string>
			<key>name</key>
			<string>comment.elis</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>comment</key>
			<string>verbatim blocks</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.elis</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>String literal</string>
			<key>end</key>
			<string>[^\\]"</string>
			<key>name</key>
			<string>string.quoted.elis</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\\\$\$?`</string>
			<key>comment</key>
			<string>Lambda parameter w/ backtick symbol</string>
			<key>end</key>
			<string>[^\\]`</string>
			<key>name</key>
			<string>string.unquoted.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Lambda parameter w/ standard symbol</string>
			<key>match</key>
			<string>\\\$\$?[_a-zA-Z][_a-zA-Z0-9]*</string>
			<key>name</key>
			<string>string.unquoted.elis</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$\$?`</string>
			<key>comment</key>
			<string>backtick enclosed variables</string>
			<key>end</key>
			<string>[^\\]`</string>
			<key>name</key>
			<string>variable.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>standard variables</string>
			<key>match</key>
			<string>\$\$?[_a-zA-Z][_a-zA-Z0-9]*</string>
			<key>name</key>
			<string>variable.elis</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>##?`</string>
			<key>comment</key>
			<string>backtick enclosed sf-bound</string>
			<key>end</key>
			<string>[^\\]`</string>
			<key>name</key>
			<string>variable.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>standard sf-bound</string>
			<key>match</key>
			<string>##?[_a-zA-Z][_a-zA-Z0-9]*</string>
			<key>name</key>
			<string>variable.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>root types</string>
			<key>match</key>
			<string>ANY|BINDING|BOOLEAN|FLOAT|INTEGER|OPTYPE|STRATEGY|STRING|SYMBOL|NONE|\^TYPE</string>
			<key>name</key>
			<string>storage.type.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean constants</string>
			<key>match</key>
			<string>(true|false|Nothing)</string>
			<key>name</key>
			<string>constant.numeric.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords</string>
			<key>match</key>
			<string>operator|is|case|-&gt;|@|=</string>
			<key>name</key>
			<string>keyword.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operator properties</string>
			<key>match</key>
			<string>associative|commutative|idempotent|identity|absorber|not</string>
			<key>name</key>
			<string>support.class.elis</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{)(:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.elis</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.elis</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>special forms</string>
			<key>end</key>
			<string>(:)(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.elis</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.elis</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.elis</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{)(!)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.elis</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.elis</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>operator definition shortcut</string>
			<key>end</key>
			<string>(:\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.elis</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.elis</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.elis</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.elis</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>lists</string>
			<key>match</key>
			<string>(%)(([!]?[ACIBD](\[.+?\])?)*)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>code bracket blocks and parameter blocks</string>
			<key>match</key>
			<string>(\{|\(|\[|\}|\)|\])</string>
			<key>name</key>
			<string>string.unquoted.elis</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>: *`</string>
			<key>comment</key>
			<string>backtick enclosed types</string>
			<key>end</key>
			<string>[^\\]`</string>
			<key>name</key>
			<string>storage.type.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>symbol types</string>
			<key>match</key>
			<string>: *[_a-zA-Z][_a-zA-Z0-9]*</string>
			<key>name</key>
			<string>storage.type.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variable names</string>
			<key>match</key>
			<string>[A-Za-z]+[A-Za-z0-9_]*</string>
			<key>name</key>
			<string>variable.other.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>hex number literal</string>
			<key>match</key>
			<string>-?0(x|X)[0-9a-fA-F]*([0-9a-fA-F]+[.])?[0-9a-fA-F]+p?</string>
			<key>name</key>
			<string>constant.numeric.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>decimal number literal</string>
			<key>match</key>
			<string>-?0(b|B)[0-1]*([0-1]+[.])?[0-1]+(e|p)?</string>
			<key>name</key>
			<string>constant.numeric.elis</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>decimal number literal</string>
			<key>match</key>
			<string>-?[0-9]*([0-9]+[.])?[0-9]+(e|p)?</string>
			<key>name</key>
			<string>constant.numeric.elis</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.elis</string>
	<key>uuid</key>
	<string>aa15f5a6-9a2f-4a5a-bd49-160c3bf3bab6</string>
</dict>
</plist>
